package com.sample  
 import com.sample.Pojo;  
 import java.util.ArrayList;  
 import java.util.HashMap;  
 import java.util.List;  
 import java.util.Map;  
 import java.util.Map.Entry;  
 rule "Get City For Thane Station"  
   when  
     pojo : Pojo($cityPlaces : cityPlaces)  
     entry : Entry() from $cityPlaces.entrySet()  
     value : String() from entry.getValue()  
     // eval(value == "Thane")  Reduce the usage of eval. So use this
     Boolean(booleanValue == true) from value == "Thane"
   then  
     System.out.println(value + " station comes under " + entry.getKey() );  
 end 